version: "3.8"

services:
  web:
    build: .  # Build the app image from the current directory
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      - POSTGRES_HOST=postgres  # Set environment variable for database host
      - POSTGRES_DB=mydatabase  # Set environment variable for database name
      - POSTGRES_USER=postgres  # Set environment variable for database user
      - POSTGRES_PASSWORD=password  # Replace with a strong password
    depends_on:
      - postgres  # Ensure the app only starts after the database is up

  postgres:
    image: postgres:latest  # Use the official PostgreSQL image
    environment:
      - POSTGRES_PASSWORD=password  # Replace with a strong password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # in the container 

volumes:
  postgres_data:  # Define a named volume in the host
